# initially wrote the config file as global variables.  Saw in 'Possible Soultion'
# about YAML so rewrote config.

en:
  prepend: "=> "
  welcome_prompt: "Welcome to Calculator! Enter your name:"
  greeting: "Hi"
  name_error: "Make sure to use a valid name"
  first_number_prompt: "What's the first number?"
  second_number_prompt: "What's the second number?"
  number_error: "Hmm... that doesn't look like a valid number"
  operator_prompt: |
    What operation would you like to perform?
        1) add
        2) subtract
        3) multiply
        4) divide
  operator_error: "Must choose 1, 2, 3 or 4"
  adding: "Adding"
  subtracting: "Subtracting"
  multiplying: "Multiplying"
  dividing: "Dividing"
  working: "the two numbers..."
  result: "The result is"
  recalculate: "Do you want to perform another calculation? (Y to calculate again)"
  goodbye: "Thank you for using calculator. Good bye!"
es:
  prepend: "=> "
  welcome_prompt: "Welcome a la calculadora! Introduzca su nombre de:"
  greeting: "Hola"
  name_error: "Make utilice un name válido"
  first_number_prompt: "¿Cuál es el primer número?"
  second_number_prompt: "¿Qué es el segundo número?"
  number_error: "Hmm... no parece ser un número válido"
  operator_prompt: |
    ¿Qué operación desea realizar?
        1) Además
        2) resta de
        3) multiplicación
        4) División de
  operator_error: "Debe elegir 1, 2, 3 o 4"
  adding: "Agregar"
  subtracting: "restando"
  multiplying: "multiplicando"
  dividing: "dividiendo"
  working: "los dos números..."
  result: "el resultado es"
  recalculate: "¿Desea realizar otro cálculo? (Y para calcular el nuevo)"
  goodbye: "Gracias por utilizar calculadora. Adiós"
